#!/usr/bin/env python3
"""Apply BlueCloud branding to a BUILT Tactical RMM frontend bundle.

WHY THIS EXISTS, AND WHY BRANDING IS NOT DONE AT SOURCE LEVEL

The deployed frontend is not built from the public source. It is the official bundle
that Tactical RMM's own updater downloads, using the sponsorship token, from
`python manage.py get_webtar_url`. That bundle is what carries the Tier 2 EE features --
Reporting in particular, because the public source ships `src/boot/integrations.ts` with
empty arrays and therefore no Reporting Manager at all.

Building from source and deploying that build silently removes Reporting. It happened:
reporting was reported broken immediately after exactly that.

So the brand is applied to the OFFICIAL bundle, after download, instead:

  * text: the product name
  * colours: Quasar's compiled defaults swapped for the BlueCloud palette
  * images: logo and favicon replaced in place, matched by CONTENT so a renamed or
    rehashed asset is still found

Nothing here touches licensing code, integration registration, or any EE gate. If a
feature is not in the bundle Amidaware served, this script does not add it -- the EE
licence forbids that, and it would also be dishonest about what has been paid for.

Re-run after EVERY update, because an update replaces dist wholesale:

    python3 src/branding/apply-to-dist.py /var/www/rmm/dist

Idempotent: running it twice changes nothing the second time.
"""
import hashlib
import os
import re
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
WEB_ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))

NAME_FROM, NAME_TO = "Tactical RMM", "BlueCloud RMM"

# Quasar's compiled defaults -> BlueCloud, from www.blueuc.com's own stylesheet.
COLOURS = {
    "#1976d2": "#00c4ff", "#1976D2": "#00C4FF",   # primary
    "#26a69a": "#007294", "#26A69A": "#007294",   # secondary
    "#1d1d1d": "#1b1319", "#1D1D1D": "#1B1319",   # dark
}

TEXT_EXT = {".js", ".css", ".html", ".json", ".mjs"}

# The official bundle renders the product name as TEXT only -- upstream puts no logo in
# the toolbar or on the login card. A source build could add an <img>; this cannot, because
# rewriting compiled render functions to insert an element is the kind of patch that breaks
# on the next release without warning.
#
# So the logo is placed with CSS instead, as a ::before on the two headings. Cosmetic,
# selector-based, and it survives a rebuild of the bundle because it never touches the
# bundle's own files -- brand.css is added alongside and linked from index.html.
BRAND_CSS = """/* BlueCloud branding. Generated by src/branding/apply-to-dist.py -- do not edit here. */

/* App header. The toolbar is dark, so the reverse (white) logo is used. */
.q-toolbar__title {
  display: flex !important;
  align-items: center;
}
.q-toolbar__title::before {
  content: "";
  display: inline-block;
  width: 30px;
  height: 24px;
  margin-right: 10px;
  flex: 0 0 auto;
  background: url("blueuc-logo-reverse.png") left center / contain no-repeat;
}

/* Login card. Light background, so the standard logo is used, above the name. */
.q-card__section .text-h4.ellipsis::before {
  content: "";
  display: block;
  width: 100%;
  height: 54px;
  margin: 0 auto 12px;
  background: url("blueuc-logo.png") center center / contain no-repeat;
}
"""


def sh(*a):
    return subprocess.run(a, check=True, capture_output=True)


def md5(path):
    h = hashlib.md5()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def patch_text(dist):
    names = colours = 0
    for root, _, files in os.walk(dist):
        for f in files:
            if os.path.splitext(f)[1].lower() not in TEXT_EXT:
                continue
            p = os.path.join(root, f)
            try:
                s = open(p, encoding="utf-8").read()
            except (UnicodeDecodeError, OSError):
                continue
            o = s
            if NAME_FROM in s:
                s = s.replace(NAME_FROM, NAME_TO)
                names += 1
            for a, b in COLOURS.items():
                if a in s:
                    s = s.replace(a, b)
                    colours += 1
            if s != o:
                open(p, "w", encoding="utf-8").write(s)
    return names, colours


def patch_images(dist):
    """Replace logo/favicon by matching UPSTREAM asset content, not filename.

    The bundler renames assets to content hashes, so filenames are unusable as
    identifiers. Matching the upstream file's bytes finds it regardless of hash.
    """
    from PIL import Image

    replaced = []
    upstream = {
        os.path.join(WEB_ROOT, "src/assets/trmm_256.png"): "logo-square.png",
        os.path.join(WEB_ROOT, "src/assets/logo.png"): "logo.png",
        os.path.join(WEB_ROOT, "public/favicon.ico"): "favicon.ico",
    }
    index = {}
    for root, _, files in os.walk(dist):
        for f in files:
            if os.path.splitext(f)[1].lower() in (".png", ".ico", ".svg", ".jpg"):
                p = os.path.join(root, f)
                index.setdefault(md5(p), []).append(p)

    for up, ours in upstream.items():
        if not os.path.exists(up):
            continue
        targets = index.get(md5(up), [])
        src = os.path.join(HERE, "assets", ours)
        for t in targets:
            # Keep the original pixel dimensions: layouts size some of these by
            # attribute and others by CSS, and a different aspect ratio would push
            # the toolbar around.
            with Image.open(t) as cur:
                w, h = cur.size
            with Image.open(src).convert("RGBA") as new:
                out = Image.new("RGBA", (w, h), (0, 0, 0, 0))
                r = new.copy()
                r.thumbnail((w, h), Image.LANCZOS)
                out.paste(r, ((w - r.size[0]) // 2, (h - r.size[1]) // 2), r)
                if t.lower().endswith(".ico"):
                    out.save(t, format="ICO")
                else:
                    out.save(t, format="PNG")
            replaced.append((os.path.basename(t), ours, "%dx%d" % (w, h)))

    # favicon.ico at the dist root is served by path, not by hash
    root_ico = os.path.join(dist, "favicon.ico")
    if os.path.exists(root_ico):
        shutil.copyfile(os.path.join(HERE, "assets", "favicon.ico"), root_ico)
        replaced.append(("favicon.ico", "favicon.ico", "root"))
    return replaced


def install_logo_css(dist):
    """Drop the logo files in and link a stylesheet from index.html.

    Idempotent: the <link> is only added when absent, and the files are overwritten
    each run so an updated logo propagates.
    """
    for src_name, out_name in (("logo-reverse.png", "blueuc-logo-reverse.png"),
                               ("logo.png", "blueuc-logo.png")):
        shutil.copyfile(os.path.join(HERE, "assets", src_name),
                        os.path.join(dist, out_name))
    open(os.path.join(dist, "brand.css"), "w", encoding="utf-8").write(BRAND_CSS)

    index = os.path.join(dist, "index.html")
    html = open(index, encoding="utf-8").read()
    link = '<link rel="stylesheet" href="brand.css">'
    if link not in html:
        # Last thing in <head>, so it wins over the bundle's own stylesheet without
        # needing !important on every rule.
        html = html.replace("</head>", "  " + link + "\n</head>", 1)
        open(index, "w", encoding="utf-8").write(html)
        return "linked"
    return "already linked"


def main():
    dist = sys.argv[1] if len(sys.argv) > 1 else "/var/www/rmm/dist"
    if not os.path.isdir(dist):
        sys.exit("no such dist: %s" % dist)

    # Refuse to brand a bundle that has lost Reporting: that is the signature of a
    # source build having been deployed over the official one, and branding it would
    # hide the real problem behind a cosmetic success.
    has_reporting = subprocess.run(
        ["grep", "-rql", "ReportTemplateForm", dist], capture_output=True
    ).returncode == 0
    if not has_reporting:
        print("WARNING: this bundle contains no Reporting UI.")
        print("         Expect the official webtar (get_webtar_url), not a source build.")

    names, colours = patch_text(dist)
    imgs = patch_images(dist)
    css_state = install_logo_css(dist)
    print("branded %s" % dist)
    print("  product name replaced in %d file(s)" % names)
    print("  colour substitutions in  %d file(s)" % colours)
    for f, src, size in imgs:
        print("  image %-16s <- %-16s (%s)" % (f, src, size))
    print("  logo css:          %s (brand.css + 2 png)" % css_state)
    print("  reporting present: %s" % ("yes" if has_reporting else "NO"))


if __name__ == "__main__":
    main()
